export default function DisclaimerPage() {
  return (
    <div className="bg-background">
      <div className="container mx-auto px-4 py-16">
        <div className="max-w-3xl mx-auto prose dark:prose-invert">
          <h1 className="text-4xl font-bold mb-8">Disclaimer</h1>
          <p>Last updated: {new Date().toLocaleDateString()}</p>

          <p>
            The information provided by Imagen Go BrainAi ("we," "us," or "our") on this website (the "Service") is for general informational purposes only. All information on the Service is provided in good faith, however we make no representation or warranty of any kind, express or implied, regarding the accuracy, adequacy, validity, reliability, availability, or completeness of any information on the Service.
          </p>

          <h2 className="text-2xl font-bold mt-6">AI Generated Content Disclaimer</h2>
          <p>
            The images and content generated by our AI models are the result of complex algorithms and are not created or vetted by humans before being displayed. As such, we cannot guarantee the accuracy, suitability, or quality of the generated content.
          </p>
          <p>
            The AI may produce images that are unexpected, inaccurate, or may not perfectly match the user's prompt. Users should be aware that the technology is probabilistic and may sometimes create artifacts or nonsensical outputs.
          </p>
          <p>
            You, the user, are solely responsible for the use of any content generated through our Service. You should review and verify any generated images for appropriateness and accuracy before using them for any purpose, especially in a commercial or public context.
          </p>

          <h2 className="text-2xl font-bold mt-6">External Links Disclaimer</h2>
          <p>
            The Service may contain links to external websites that are not provided or maintained by or in any way affiliated with Imagen Go BrainAi. Please note that the Imagen Go BrainAi does not guarantee the accuracy, relevance, timeliness, or completeness of any information on these external websites.
          </p>

          <h2 className="text-2xl font-bold mt-6">No Professional Advice</h2>
          <p>
            The information provided by the Service is not a substitute for professional advice. All content is for informational purposes only. Accordingly, before taking any actions based upon such information, we encourage you to consult with the appropriate professionals.
          </p>

          <p>
            UNDER NO CIRCUMSTANCE SHALL WE HAVE ANY LIABILITY TO YOU FOR ANY LOSS OR DAMAGE OF ANY KIND INCURRED AS A RESULT OF THE USE OF THE SERVICE OR RELIANCE ON ANY INFORMATION PROVIDED ON THE SERVICE. YOUR USE OF THE SERVICE AND YOUR RELIANCE ON ANY INFORMATION ON THE SERVICE IS SOLELY AT YOUR OWN RISK.
          </p>
        </div>
      </div>
    </div>
  );
}
